export const CREATE_TICKET_START = 'CREATE_TICKET_START'
export const CREATE_TICKET_SUCCESS = 'CREATE_TICKET_SUCCESS'
export const CREATE_TICKET_FAILURE = 'CREATE_TICKET_FAILURE'

export const GET_TICKETS_START = 'GET_TICKETS_START'
export const GET_TICKETS_SUCCESS = 'GET_TICKETS_SUCCESS'
export const GET_TICKETS_FAILURE = 'GET_ITEMS_FAILURE'
